apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 3001
    protocol: TCP
    name: nodejs-api
  selector:
    app: {{ .Values.appName }}
    tier: backend
  type: NodePort
